runtime: nodejs20
env: standard

env_variables:
  NODE_ENV: production
  PORT: 8080
  JWT_SECRET: your-super-secret-jwt-key-change-in-production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always 