name: mariela-job-platform
services:
- name: mariela-backend
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 8080
  - key: JWT_SECRET
    value: your-super-secure-production-secret-key-here
  health_check:
    http_path: /health 